"""Add remaining missing columns

Revision ID: 5ee2b5ff018a
Revises: b4fb2644d4b6
Create Date: 2026-08-20 23:50:48.441531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee2b5ff018a'
down_revision: Union[str, Sequence[str], None] = 'b4fb2644d4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ad_real_estate_details', 'ads', ['ad_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_ad_search_attributes'), table_name='ad_search_index', postgresql_using='gin')
    op.drop_index(op.f('idx_ad_search_filters'), table_name='ad_search_index')
    op.drop_index(op.f('idx_ad_search_structured'), table_name='ad_search_index')
    op.drop_index(op.f('idx_ad_search_text_trgm'), table_name='ad_search_index', postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_ad_search_vector'), table_name='ad_search_index', postgresql_using='gin')
    op.alter_column('ads', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ads', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ads', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('ads', 'location',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('ads', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ORGANIC_USER', 'SCRAPER_BOT', 'SCRAPER', name='sourcetype'),
               existing_nullable=True,
               existing_server_default=sa.text("'ORGANIC_USER'::character varying"))
    op.drop_index(op.f('idx_ads_location_pattern'), table_name='ads', postgresql_ops={'location': 'text_pattern_ops'})
    op.create_index(op.f('ix_ads_id'), 'ads', ['id'], unique=False)
    op.create_index(op.f('ix_ads_primary_image_hash'), 'ads', ['primary_image_hash'], unique=False)
    op.create_index(op.f('ix_ads_source_url'), 'ads', ['source_url'], unique=False)
    op.create_index(op.f('ix_ai_training_logs_id'), 'ai_training_logs', ['id'], unique=False)
    op.alter_column('categories', 'icon_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.alter_column('facebook_autopost_rules', 'region_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('facebook_autopost_rules_region_name_key'), 'facebook_autopost_rules', type_='unique')
    op.create_index(op.f('ix_facebook_autopost_rules_id'), 'facebook_autopost_rules', ['id'], unique=False)
    op.create_index(op.f('ix_facebook_autopost_rules_region_name'), 'facebook_autopost_rules', ['region_name'], unique=True)
    op.create_index(op.f('ix_live_tickers_id'), 'live_tickers', ['id'], unique=False)
    op.create_unique_constraint('uq_region_city_name_ar', 'regions', ['city_id', 'name_ar'])
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.alter_column('user_metrics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('user_metrics_user_id_key'), 'user_metrics', type_='unique')
    op.create_index(op.f('ix_user_metrics_id'), 'user_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_user_reviews_id'), 'user_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_user_reviews_target_user_id'), 'user_reviews', ['target_user_id'], unique=False)
    op.add_column('users', sa.Column('wallet_balance', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.drop_constraint(op.f('users_mobile_number_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_mobile_number_key'), 'users', ['mobile_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'wallet_balance')
    op.drop_index(op.f('ix_user_reviews_target_user_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_reviews_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_metrics_id'), table_name='user_metrics')
    op.create_unique_constraint(op.f('user_metrics_user_id_key'), 'user_metrics', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_metrics', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_constraint('uq_region_city_name_ar', 'regions', type_='unique')
    op.drop_index(op.f('ix_live_tickers_id'), table_name='live_tickers')
    op.drop_index(op.f('ix_facebook_autopost_rules_region_name'), table_name='facebook_autopost_rules')
    op.drop_index(op.f('ix_facebook_autopost_rules_id'), table_name='facebook_autopost_rules')
    op.create_unique_constraint(op.f('facebook_autopost_rules_region_name_key'), 'facebook_autopost_rules', ['region_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('facebook_autopost_rules', 'region_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.alter_column('categories', 'icon_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_training_logs_id'), table_name='ai_training_logs')
    op.drop_index(op.f('ix_ads_source_url'), table_name='ads')
    op.drop_index(op.f('ix_ads_primary_image_hash'), table_name='ads')
    op.drop_index(op.f('ix_ads_id'), table_name='ads')
    op.create_index(op.f('idx_ads_location_pattern'), 'ads', ['location'], unique=False, postgresql_ops={'location': 'text_pattern_ops'})
    op.alter_column('ads', 'source_type',
               existing_type=sa.Enum('ORGANIC_USER', 'SCRAPER_BOT', 'SCRAPER', name='sourcetype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'ORGANIC_USER'::character varying"))
    op.alter_column('ads', 'location',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ads', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('ads', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('ads', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('idx_ad_search_vector'), 'ad_search_index', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_ad_search_text_trgm'), 'ad_search_index', ['search_text'], unique=False, postgresql_ops={'search_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_ad_search_structured'), 'ad_search_index', ['category_id', 'city_id', 'region_id', 'deal_type', 'price'], unique=False)
    op.create_index(op.f('idx_ad_search_filters'), 'ad_search_index', ['category_id', 'city_id', 'region_id', 'deal_type', 'price'], unique=False)
    op.create_index(op.f('idx_ad_search_attributes'), 'ad_search_index', ['attributes_jsonb'], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'ad_real_estate_details', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
