"""Add RegionAlias table

Revision ID: f44940494461
Revises: aae1c66e64e9
Create Date: 2026-07-23 12:46:03.007154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44940494461'
down_revision: Union[str, Sequence[str], None] = 'aae1c66e64e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name')
    )
    op.create_index(op.f('ix_region_aliases_id'), 'region_aliases', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_aliases_id'), table_name='region_aliases')
    op.drop_table('region_aliases')
    # ### end Alembic commands ###